### ISSUE TITLE
NPE with setHTMLText()

### ISSUE THREAD

**Issue by MeDVen** [MeDVen/LimeChat#1]
NPE when set html text on init control. This is not crush application.
Exception appears on Windows 10 and Mac OS X.

Testing on Linux (KDE4), Mac Os X and Windows 10.

StackTrace:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at com.sun.javafx.scene.web.skin.HTMLEditorSkin.updateToolbarState(HTMLEditorSkin.java:955)
    at com.sun.javafx.scene.web.skin.HTMLEditorSkin.lambda$populateToolbars$13(HTMLEditorSkin.java:580)
    at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
    at javafx.scene.control.ComboBoxBase.setValue(ComboBoxBase.java:150)
    at com.sun.javafx.scene.web.skin.HTMLEditorSkin.updateToolbarState(HTMLEditorSkin.java:900)
    at com.sun.javafx.scene.web.skin.HTMLEditorSkin.lambda$setHTMLText$11(HTMLEditorSkin.java:487)
    at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by MeDVen** [comment]
Just needed full html code. Linux and Windows ignore this, but Mac OS X not.

Example:

Right:

```
<html><body style="font-family: Helvetica, sans-serif; color: #96b946; "
            + "background-color: #828282; border: 1px solid black"></body><html>
```

Wrong:

```
<body style="font-family: Helvetica, sans-serif; color: #96b946; "
            + "background-color: #828282; border: 1px solid black"></body>
```

**Comment by MeDVen** [comment]
Still falling on Mac OS X and Windows 10 if JS method onLoad() included into body tag.

**Comment by rlapin92** [comment]
We can try to add javascript document ready function instead of inline focus in body onload and maybe it can solve our problem.

**Comment by MeDVen** [comment]
Maybe need overide updateToolbarState() in HTMLEditorSkin,
